// Generated by CoffeeScript 1.8.0
(function() {
  var fs, http, play, request, rest;

  http = require('http');

  request = require('request');

  rest = require('restless');

  play = require('play-audio');

  fs = require('fs');

  module.exports = {
    phrase: function(req, res) {
      var foo;
      foo = req.query.q;
      return rest.get('http://localhost:8082/api/say?q=' + req.query.q, function(error, data) {
        var filePath, soundUrl, splitSoundUrl;
        soundUrl = "" + data;
        splitSoundUrl = soundUrl;
        filePath = parseMy.filenameToPath(foo);
        return console.log(filePath);
      });
    }
  };

}).call(this);

//# sourceMappingURL=SayController.js.map
