// Generated by CoffeeScript 1.8.0

/* helperService methods for general manipulation */

(function() {
  var download, fs, iPromise, path;

  fs = require('fs-extra');

  path = require('path');

  download = require('simpledownload');

  iPromise = require('promisy');

  module.exports = {
    semanticFilePath: function(string, result) {
      var sPath;
      sPath = path.join('voice/', "" + string);
      result = "../../" + sPath;
      fs.mkdirs("../../" + sPath)(function(err) {
        if (err) {
          return console.error(err);
        } else {
          return function() {
            return callback(result);
          };
        }
      });
      return console.log("I have made the requested directories");
    },
    phraseDownload: function(string) {
      return iPromise(function(next) {
        semanticFilePath(string);
        return console.log("first");
      });
    }
  };

  download("http://194.158.21.231:8081/MESSAGES/  + 012099097112101108097071114111117112/ + AcapelaGroup_WebDemo_HTML/sounds/94327397_d7e5fc3960987.mp3', __dirname + '/test.mp3", function(err) {
    return console.log('error');
  });

}).call(this);

//# sourceMappingURL=createMy.js.map
