// Generated by CoffeeScript 1.8.0

/* helperService methods for general manipulation */

(function() {
  var fs;

  fs = require('fs-extra');

  module.exports = {
    semanticFilePath: function(string) {
      var sPath;
      sPath = _path.join(_dirname, "" + string);
      return fs.mkdirs(sPath, function(err) {
        if (err) {
          console.error(err);
        }
        return console.log("we're good");
      });
    }
  };

}).call(this);

//# sourceMappingURL=createMy.js.map
