// Generated by CoffeeScript 1.8.0

/*request = require 'request' */

(function() {
  var fs, http, request;

  fs = require('fs');

  http = require('http');

  request = require('request');

}).call(this);

//# sourceMappingURL=Now.js.map
