// Generated by CoffeeScript 1.8.0
(function() {
  var _;

  _ = require('lodash');

  module.exports = {
    filenameToPath: function(string) {
      var fileName, newPath;
      fileName = "" + string;
      newPath = fileName.replace(" ", "/");
      return newPath;
    }
  };

}).call(this);

//# sourceMappingURL=parseMy.js.map
